- name: add the string This is my CentOS VM to the conditional file
  hosts: linux
 
  tasks:
     - blockinfile:
          path: /tmp/conditional
          insertafter: EOF
          backup: yes
          state: present
          block: |
           Domains: canadaeast.cloudapp.azure.com
       when: 
          - ansible_distribution_version == "8.2" 
          - ansible_kernel == "4.18.0-193.el8.x86_64"




