- name: create muliple user in loop
  hosts: linux 

  tasks:  
   - name: create group and users 
     group:
       name: ritugroup
       state: present
       gid: 5000
   - name: Create users with group_vars
     user:
        name: "{{ item.username }}"
        uid: "{{ item.userid }}"
        groups: ritugroup
        append: 1
        home: /home/ "{{ item.username }}"
        state: present
     loop: "{{ userinfo }}"
