- name: Playbook to copy file
  become: true
  hosts: ansible47-c-vm-dns-1
   
  tasks:
    - name: copy file 
      copy:
        src: /etc/issue
        dest: /etc/issue
        owner: user4001
        group: cloudadminas
        mode: "444"
    - name: Set timezone to America/Edmonton
      timezone:
         name: America/Edmonton  
