---
- name: Remove additonal packages on CentOS/RHEL 
  package:
    name: "{{ package }}"
    state: absent
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
  tags:
     - packages
