---
- name: Install additonal packages on CentOS/RHEL
  yum:
    name: "{{ package }}"
    state: present
    update_cache: yes
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
  tags:
     - packages 

